export const UPDATE_MASTER_TABLE = 'UPDATE_MASTER_TABLE'
export const MUTATE_AUTHENTICATION_INFO = 'MUTATE_AUTHENTICATION_INFO'
export const MUTATE_LOGOUT = 'MUTATE_LOGOUT'
export const MUTATE_COME_BACK = 'MUTATE_COME_BACK'